locale                   : "en-US"
title                    : "lmao"
description              : "i do things sometimes probably"
url                      : https://thecatontheceiling.github.io
baseurl                  : ""
repository               : "thecatontheceiling/thecatontheceiling.github.io"
theme                    : jekyll-theme-minimal
