locale                   : "en-US"
title                    : "lmao"
description              : "i do things sometimes probably"
baseurl                  : https://thecatontheceiling.github.io
repository               : "thecatontheceiling/thecatontheceiling.github.io"
theme                    : jekyll-theme-minimal
